### ISSUE TITLE
Seats number per table is completely ignored

### ISSUE THREAD

**Issue by davidulus** [vanadiuz/table-reservation#11]
Hi Ivan. I´m using your plugin for ball night event and experiencing some troubles. It allows to reserve more seats per table then it should be possible. You posted https://birrabarbanera.it/serate-fuori-moda/ as example in WP support forum, but I tested it also there and it allows me to book 300 hundred persons per one table => number of seats for cafe is completely ignored.

**Comment by vanadiuz** [comment]
Hi David, 
you could add code, which will check it and return error in place after line 234 of table-reservation.php.
But in general, thanks! 👍
