### ISSUE TITLE
Enhancement: more reservations per table

### ISSUE THREAD

**Issue by davidulus** [vanadiuz/table-reservation#12]
Hi Ivan. My use-case is ball night event, where can be more persons per one table. Tables are big, e.g. for 20 persons. When 1 visitor reserve table it´s not possible for another visitor to book this table anymore.
It would be cool, if there will be some checkbox at table in admin, which will allow for more reservations per table. I´m able to help on backend part if you are interested, but I´m not experienced in Vue.

**Comment by vanadiuz** [comment]
Hi, 
All you need to do is possible without Vue!
