### ISSUE TITLE
Any chance for manual approval for reservations? [plugin is possible SPAM source]

### ISSUE THREAD

**Issue by Kisuke-CZE** [vanadiuz/table-reservation#15]
Hi,

your plugin looks great. Just how I imagine simple reservation for small cafe/restaurant.
But I see one big hole in this. It sends e-mail to foreign domain without manual approval. And I can't see any option in settings to achieve this.
Not sure if Pro version does not have such feature (I will definitely go with Pro if I want to use it on production).

The main problem is, that this plugin in this state is vulnerable. It is possible source of spam when some robot starts to make reservations with random foreign e-mail adresses. Manual approval could fix that.

Another thing is, that not everyone wants to confirm reservation right away. (Of course you can change the notification text. So it is kind of solution)

**Comment by vanadiuz** [comment]
Hi,
Thank you very much for paying attention to this. Now I am very busy, but I’ll change this by the summer.

**Comment by vanadiuz** [comment]
Hi,
Well, if someone has nothing to spend their time on, then this is possible. I have thought to add the Google captcha to the plugin in the future.

**Comment by Kisuke-CZE** [comment]
Hi,

thanks for response. Any improvement would be nice.
Since spambots have plenty of time, it could be real problem.
It is not the problem until someone does not discover this. If someone wants to harm you, It's too easy to send spambot on your webform. Your mailservers can easily lose reputation. If you are on shared webhosting it can lead to shutting down your website.
