### ISSUE TITLE
Untranslatable character '№' in assets/js/app.504a35b9300c6a960f4b.js

### ISSUE THREAD

**Issue by Kisuke-CZE** [vanadiuz/table-reservation#16]
Hi,

i just found there is character '№' in assets/js/app.504a35b9300c6a960f4b.js which is used before table number in reservation form. It is not possible to translate it using language module. Any chance for change? (I just rewrote it in .js itself) Meaning of this character is not clear in every language :(

**Comment by vanadiuz** [comment]
Hi,
Thank you very much for paying attention to this. Now I am very busy, but I’ll change this by the summer.
