### ISSUE TITLE
Blank page after reservation is sent

### ISSUE THREAD

**Issue by Kisuke-CZE** [vanadiuz/table-reservation#17]
Hi,

I found another small thing. When I place plugin on blank page (which is only for the purpose of reservation), it looks weird when I sent the reservation and plugin just disappears.

When user sent a reservation there is message for few seconds saying 'Thank you for your reservation'. But after few seconds it disappears and there is only blank page.

Is it possible to add some setting which will allow to keep displayed message 'Thank you for your reservation'. Or forward customer back to homepage?

This is just cosmetics. But would be nice, since whole idea of this plugin seems to be nice and easy way for customer to book his favourite table.

**Comment by vanadiuz** [comment]
Nice Idea! I will definitely implement it, thanks!

**Comment by katgrach** [comment]
fixed in https://github.com/vanadiuz/table-reservation/commit/f668dc24aa7a1dfda49a2e7f6bd3a438ba84f6c2
