### ISSUE TITLE
[Feature] pre-paid table (paypal or other platforms)

### ISSUE THREAD

**Issue by DaBlitzStein** [vanadiuz/table-reservation#21]
I suggest this because on our gaming center the weekend night reservations are pre-paid, to prevent churn of the customer and avoid empty spaces.

Thank you in advance!

**Comment by vanadiuz** [comment]
Thank you very much for your message. Many people ask for this feature. During the summer, and maybe earlier, it will appear in the plugin.

**Comment by DaBlitzStein** [comment]
Will be perfect! Thank you in advance.

**Comment by vanadiuz** [comment]
I decided not to add this feature to the plugin, because I do not have enough time to support it. Sorry, I hope for your understanding.
