### ISSUE TITLE
Is it possible to prepare a table layout for the restaurant lounge?

### ISSUE THREAD

**Issue by ahmetoktay1234** [vanadiuz/table-reservation#26]
As far as I can tell from the demo video, the table layout cannot be prepared in this plugin. or the explanation  was considered unnecessary.

In any case, please tell me how I can handle this, preparing the table layout for the restaurant lounge.!
[github.com vanadiuz-table-reservation ISSUES new.pdf](https://github.com/vanadiuz/table-reservation/files/3675655/github.com.vanadiuz-table-reservation.ISSUES.new.pdf)

**Comment by vanadiuz** [comment]
You have to use anouther software to create grafical repsentation of cafes pland. 3ds max for example
