### ISSUE TITLE
Does not display reserved tables consistently across browsers

### ISSUE THREAD

**Issue by freshynek** [vanadiuz/table-reservation#28]
I use your Table reservation on www.original-lounge.cz website. The plugin shows available tables, when they are already reserved.
I found that sometimes, not always, a table is shown green as available, but it is actually taken, already reserved. This happens especially in Safari. But sometimes even on Chrome. When I try to book a reserved table it allows me to reserve until the point where I type in my name. But the table should be shown as red / reserved. So I should not even start with the reservation.

Thank you

**Comment by vanadiuz** [comment]
Hi, there's a known bug, when taken right now tables are green. They still couldn't be booked. So it's not really critical. But I will fix it in the future.
Try to set up "Late Reservations" to "At least 4 hours in advance". It will solve the problem.

**Comment by vanadiuz** [comment]
Now it is fixed. Please, download last version of plugin from this repository.
