### ISSUE TITLE
Some additional requirements ?

### ISSUE THREAD

**Issue by laurent-d** [vanadiuz/table-reservation#4]
Hi,

The plugin doesn't work on fresh install of wordpress (WordPress 4.9.4) locally and on managed server.
The debug console still display : Failed to load resource: the server responded with a status of 404 (Not Found)
/wp-json/wp/v2/trem-reservation/?per_page=100 Failed to load resource: the server responded with a status of 404 (Not Found) 
Do i need to install other plugin to make it work ?

Many thanks

**Comment by laurent-d** [comment]
Self reply, the wp-json is available throught home_url()./wp-json/wp/v2/trem-reservation/?per_page=100 not site_url()./wp-json/wp/v2/trem-reservation/?per_page=100

I think there is a mistake on table-reservation.php on line 390 and 391

**Comment by vanadiuz** [comment]
Hi laurent, 

Very sorry for the fact that I answer only now.
I've tested .zip from github, everything work correctly. Did you create scheme of cafe? 
You can try to install plugin from WordPress Repository. There is the same version.

**Comment by vanadiuz** [comment]
p.s. for developing you should open 
uncomment wp_register_script( 'tremtr-app', 'http://localhost:8080/app.js' , '', '', true ); in table-reservation.php and comment three strings above
