### ISSUE TITLE
Secondary method for selecting a seat

### ISSUE THREAD

**Issue by tzeumer** [vanadiuz/table-reservation#42]
We recently discovered this very nice plugin. We are not a cafe, restaurant, internet cafe or night club, but a library. And as such not exactly large - due to corona we have "only" 92 seats on two levels. This (https://mars.tub.tuhh.de/) works pretty nicely on larger screens and the image is a real benefit.

But on mobiles it is a bit harder to select a seat. Also you can only scroll down to the booking button by touching outside the canvas, which is somewhat confusing.

Therefore I wondered, if I could just add a select menu after the time select slider as secondary method for choosing a seat. And I'd move the booking button above the image, too. 

While the latter is no problem, the select menu is far more challenging, than I thought. I've no experience with vue.js and fabric.js. I only (?) need a select menu that simulates a click (or triggers [this oberserve method](https://collaborating.tuhh.de/tub/dd/applications/tub.reserve/-/blob/master/tremtr/src/App.vue#L1220)) on a specific (available) table id. 

Maybe this would be easy to do? I'd appreciate any hint.

Anyway, much obliged for this very useful plugin. :)

**Comment by vanadiuz** [comment]
Hi, 

> Therefore I wondered, if I could just add a select menu after the time select slider as secondary method for choosing a seat. And I'd move the booking button above the image, too.

It requires solid understanding of what is happening in the code. Because canvas is deeply coupled with all others elements of form. 
Mobile version is the weakest part of the plugin. And I have no idea how to do it good. The only advice from me could be a warning for users to reserve a seat using horizontal mode on smartphone.

**Comment by tzeumer** [comment]
Thanks for the quick reply. 

Yes, mobile and images is always a challenge. :)
