### ISSUE TITLE
SMS urgent request

### ISSUE THREAD

**Issue by westronman** [vanadiuz/table-reservation#56]
Hi there. Firstly, you saved my life. This plugin is fantastic! Does (almost) everything I needed. I wasted a ton of time on others until I found this - great work!! However, I need to be able to send an sms notification whenever a new booking is made for a cafe (I have 3). The sms notification needs to be sent to the mobile number captured in the booking, along with the booking details (e.g. cafe, time, table number etc.). Can you suggest how I could do this or do you have any other plugins that would enable me to do this? I know about Twilio but I'm not a developer :-) thanks - Neil.

**Comment by vanadiuz** [comment]
Hi, 
unfortunately I'm not supporting it anymore. But in your place, I would use Twilio as well. Solving such problems without programming skills is painful. 
Best,
V
