### ISSUE TITLE
Custom Table Names

### ISSUE THREAD

**Issue by MarkRabey** [vanadiuz/table-reservation#7]
First of all, great plugin. Saved me loads of time so far.

I have a client I'm build a site for that doesn't number all their tables starting at 1. In some cases they may also add a letter. For example, their patio tables might be "P-1", "P-2", and so on.

I'm wondering if you plan on implementing custom tables names in the near future? I could take a stab at it myself, but knowing the code, you can probably do it a lot faster.

**Comment by vanadiuz** [comment]
I will think about it. Thanks for the idea!

**Comment by vanadiuz** [comment]
In my opinion, this is superfluous information. Tell your client about the pro version and it will give up the prefix in the names.
