### ISSUE TITLE
Cannot show all content

### ISSUE THREAD

**Issue by trngkn** [vanadiuz/table-reservation#9]
hiii, i've tested your plugin in my demo site but after creat scheme and put shortcode to new page, its not show all content. This is my demo site for ex., Can you help me fix this issues, plz? 
http://demovt.tk/sample-page/

**Comment by vanadiuz** [comment]
Hi, could you please attach screenshot or renew plugin on your website?

**Comment by trngkn** [comment]
i've reactive plug-in on my website, hope you'll enter my demo website above. Sr for my bad english

**Comment by vanadiuz** [comment]
Please, provide me credentials [here ](https://true-emotions.studio/support/)to see where is a problem.
